name: Demo - Deployment Metrics (DORA)
on:
  push:
    branches:
      - master
  workflow_dispatch:
    status:
      description: 'Deployment status'
      default: 'success'
    type: choice
    options:
    - success
    - failure

jobs:
  simulate-deploy:
    name: Force deployment
    runs-on: ubuntu-latest
    steps:
    - name: 'Report Deployment Succeeded'
      if: ${{ inputs.status == 'success' }}
      uses: cto-ai/action@v1.3.0-rc1
      with:
        team_id: ${{ secrets.CTOAI_TEAM_STG }}
        token: ${{ secrets.CTOAI_TOKEN_STG }}
        event_name: "deployment"
        event_action: "succeeded"
    - name: 'Report Deployment Failed'
      if: ${{ inputs.status != 'success' }}
      uses: cto-ai/action@v1.3.0-rc1
      with:
        team_id: ${{ secrets.CTOAI_TEAM_STG }}
        token: ${{ secrets.CTOAI_TOKEN_STG }}
        event_name: "deployment"
        event_action: "failed"
