name: Demo - Deployment Metrics (DORA)
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  simulate-deploy:
    name: Force deployment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Report Deployment Succeeded
      uses: cto-ai/action@ee1a09518ae0c05ce4f41e1ff365cb2ac68dbbe8
      id: ctoai-deployment-succeeded
      with:
        team_id: ${{ secrets.CTOAI_TEAM_STG }}
        token: ${{ secrets.CTOAI_TOKEN_STG }}
        event_name: "deployment"
        event_action: "succeeded"
