name: Demo - Release trigger
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      selector:
        description: 'selector'
        default: 'time'
        required: false
jobs:
  print:
    name: Setup
    runs-on: ubuntu-latest
    steps:
    - name: "Print inputs"
      run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Selector: ${{ github.event.inputs.selector }}"   
